export const CONVERSATION_STATES = {
  INICIO: "INICIO",

  MOSTRANDO_MENU: "MOSTRANDO_MENU",

  PREGUNTANDO_NOMBRE: "PREGUNTANDO_NOMBRE",

  PREGUNTANDO_DIRECCION: "PREGUNTANDO_DIRECCION",

  PREGUNTANDO_PAGO: "PREGUNTANDO_PAGO",

  CONFIRMANDO_PEDIDO: "CONFIRMANDO_PEDIDO",

  ESPERANDO_AGENTE: "ESPERANDO_AGENTE",

  PREGUNTANDO_MODO_ENTREGA: "PREGUNTANDO_MODO_ENTREGA",

  WAITING_FOR_REMOVAL: "WAITING_FOR_REMOVAL",

  PROPUESTA_VIP: "PROPUESTA_VIP",

  POST_VENTA: "POST_VENTA",

  ESPERANDO_COMPROBANTE: "ESPERANDO_COMPROBANTE",

  AWAITING_AMBIGUOUS_SELECTION: "AWAITING_AMBIGUOUS_SELECTION",
};

export default CONVERSATION_STATES;
